const baseSetCards = [
  {
    id: "base1-1",
    name: "Alakazam",
    imageUrl: "https://images.pokemontcg.io/base1/1.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/1_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Stage2",
    number: "1",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-2",
    name: "Blastoise",
    imageUrl: "https://images.pokemontcg.io/base1/2.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/2_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Stage2",
    number: "2",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-3",
    name: "Chansey",
    imageUrl: "https://images.pokemontcg.io/base1/3.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/3_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "3",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-4",
    name: "Charizard",
    imageUrl: "https://images.pokemontcg.io/base1/4.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/4_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Stage2",
    number: "4",
    artist: "Mitsuhiro Arita",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-5",
    name: "Clefairy",
    imageUrl: "https://images.pokemontcg.io/base1/5.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/5_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "5",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-6",
    name: "Gyarados",
    imageUrl: "https://images.pokemontcg.io/base1/6.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/6_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "6",
    artist: "Mitsuhiro Arita",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-7",
    name: "Hitmonchan",
    imageUrl: "https://images.pokemontcg.io/base1/7.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/7_hires.png",
    types: ["Fighting"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "7",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-9",
    name: "Magneton",
    imageUrl: "https://images.pokemontcg.io/base1/9.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/9_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "9",
    artist: "Keiji Kinebuchi",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-10",
    name: "Mewtwo",
    imageUrl: "https://images.pokemontcg.io/base1/10.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/10_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "10",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-11",
    name: "Nidoking",
    imageUrl: "https://images.pokemontcg.io/base1/11.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/11_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Stage2",
    number: "11",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-12",
    name: "Ninetales",
    imageUrl: "https://images.pokemontcg.io/base1/12.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/12_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "12",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-13",
    name: "Poliwrath",
    imageUrl: "https://images.pokemontcg.io/base1/13.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/13_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Stage2",
    number: "13",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-14",
    name: "Raichu",
    imageUrl: "https://images.pokemontcg.io/base1/14.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/14_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "14",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-15",
    name: "Venusaur",
    imageUrl: "https://images.pokemontcg.io/base1/15.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/15_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Stage2",
    number: "15",
    artist: "Mitsuhiro Arita",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-16",
    name: "Zapdos",
    imageUrl: "https://images.pokemontcg.io/base1/16.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/16_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "16",
    artist: "Ken Sugimori",
    rarity: "Holo Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-17",
    name: "Beedrill",
    imageUrl: "https://images.pokemontcg.io/base1/17.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/17_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Stage2",
    number: "17",
    artist: "Ken Sugimori",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-18",
    name: "Dragonair",
    imageUrl: "https://images.pokemontcg.io/base1/18.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/18_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "18",
    artist: "Mitsuhiro Arita",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-19",
    name: "Dugtrio",
    imageUrl: "https://images.pokemontcg.io/base1/19.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/19_hires.png",
    types: ["Fighting"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "19",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-20",
    name: "Electabuzz",
    imageUrl: "https://images.pokemontcg.io/base1/20.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/20_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "20",
    artist: "Ken Sugimori",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-21",
    name: "Electrode",
    imageUrl: "https://images.pokemontcg.io/base1/21.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/21_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "21",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-22",
    name: "Pidgeotto",
    imageUrl: "https://images.pokemontcg.io/base1/22.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/22_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "22",
    artist: "Ken Sugimori",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-23",
    name: "Arcanine",
    imageUrl: "https://images.pokemontcg.io/base1/23.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/23_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "23",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-24",
    name: "Charmeleon",
    imageUrl: "https://images.pokemontcg.io/base1/24.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/24_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "24",
    artist: "Mitsuhiro Arita",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-25",
    name: "Dewgong",
    imageUrl: "https://images.pokemontcg.io/base1/25.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/25_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "25",
    artist: "Mitsuhiro Arita",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-26",
    name: "Dratini",
    imageUrl: "https://images.pokemontcg.io/base1/26.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/26_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "26",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-27",
    name: "Farfetch'd",
    imageUrl: "https://images.pokemontcg.io/base1/27.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/27_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "27",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-28",
    name: "Growlithe",
    imageUrl: "https://images.pokemontcg.io/base1/28.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/28_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "28",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-29",
    name: "Haunter",
    imageUrl: "https://images.pokemontcg.io/base1/29.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/29_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "29",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-30",
    name: "Ivysaur",
    imageUrl: "https://images.pokemontcg.io/base1/30.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/30_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "30",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-31",
    name: "Jynx",
    imageUrl: "https://images.pokemontcg.io/base1/31.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/31_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "31",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-32",
    name: "Kadabra",
    imageUrl: "https://images.pokemontcg.io/base1/32.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/32_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "32",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-33",
    name: "Kakuna",
    imageUrl: "https://images.pokemontcg.io/base1/33.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/33_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "33",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-34",
    name: "Machoke",
    imageUrl: "https://images.pokemontcg.io/base1/34.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/34_hires.png",
    types: ["Fighting"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "34",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-35",
    name: "Magikarp",
    imageUrl: "https://images.pokemontcg.io/base1/35.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/35_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "35",
    artist: "Mitsuhiro Arita",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-36",
    name: "Magmar",
    imageUrl: "https://images.pokemontcg.io/base1/36.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/36_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "36",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-37",
    name: "Nidorino",
    imageUrl: "https://images.pokemontcg.io/base1/37.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/37_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "37",
    artist: "Mitsuhiro Arita",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-38",
    name: "Poliwhirl",
    imageUrl: "https://images.pokemontcg.io/base1/38.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/38_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "38",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-39",
    name: "Porygon",
    imageUrl: "https://images.pokemontcg.io/base1/39.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/39_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "39",
    artist: "TomoakiImakuni",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-40",
    name: "Raticate",
    imageUrl: "https://images.pokemontcg.io/base1/40.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/40_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "40",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-41",
    name: "Seel",
    imageUrl: "https://images.pokemontcg.io/base1/41.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/41_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "41",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-42",
    name: "Wartortle",
    imageUrl: "https://images.pokemontcg.io/base1/42.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/42_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "42",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-43",
    name: "Abra",
    imageUrl: "https://images.pokemontcg.io/base1/43.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/43_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "43",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-44",
    name: "Bulbasaur",
    imageUrl: "https://images.pokemontcg.io/base1/44.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/44_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "44",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-45",
    name: "Caterpie",
    imageUrl: "https://images.pokemontcg.io/base1/45.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/45_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "45",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-46",
    name: "Charmander",
    imageUrl: "https://images.pokemontcg.io/base1/46.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/46_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "46",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-47",
    name: "Diglett",
    imageUrl: "https://images.pokemontcg.io/base1/47.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/47_hires.png",
    types: ["Fighting"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "47",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-48",
    name: "Doduo",
    imageUrl: "https://images.pokemontcg.io/base1/48.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/48_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "48",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-49",
    name: "Drowzee",
    imageUrl: "https://images.pokemontcg.io/base1/49.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/49_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "49",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-50",
    name: "Gastly",
    imageUrl: "https://images.pokemontcg.io/base1/50.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/50_hires.png",
    types: ["Psychic"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "50",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-51",
    name: "Koffing",
    imageUrl: "https://images.pokemontcg.io/base1/51.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/51_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "51",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-52",
    name: "Machop",
    imageUrl: "https://images.pokemontcg.io/base1/52.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/52_hires.png",
    types: ["Fighting"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "52",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-53",
    name: "Magnemite",
    imageUrl: "https://images.pokemontcg.io/base1/53.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/53_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "53",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-54",
    name: "Metapod",
    imageUrl: "https://images.pokemontcg.io/base1/54.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/54_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "54",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-55",
    name: "Nidoran♂",
    imageUrl: "https://images.pokemontcg.io/base1/55.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/55_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "55",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-56",
    name: "Onix",
    imageUrl: "https://images.pokemontcg.io/base1/56.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/56_hires.png",
    types: ["Fighting"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "56",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-57",
    name: "Pidgey",
    imageUrl: "https://images.pokemontcg.io/base1/57.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/57_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "57",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-58",
    name: "Pikachu",
    imageUrl: "https://images.pokemontcg.io/base1/58.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/58_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "58",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-59",
    name: "Poliwag",
    imageUrl: "https://images.pokemontcg.io/base1/59.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/59_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "59",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-60",
    name: "Ponyta",
    imageUrl: "https://images.pokemontcg.io/base1/60.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/60_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "60",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-61",
    name: "Rattata",
    imageUrl: "https://images.pokemontcg.io/base1/61.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/61_hires.png",
    types: ["Colorless"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "61",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-62",
    name: "Sandshrew",
    imageUrl: "https://images.pokemontcg.io/base1/62.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/62_hires.png",
    types: ["Fighting"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "62",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-63",
    name: "Squirtle",
    imageUrl: "https://images.pokemontcg.io/base1/63.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/63_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "63",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-64",
    name: "Starmie",
    imageUrl: "https://images.pokemontcg.io/base1/64.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/64_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Stage1",
    number: "64",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-65",
    name: "Staryu",
    imageUrl: "https://images.pokemontcg.io/base1/65.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/65_hires.png",
    types: ["Water"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "65",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-66",
    name: "Tangela",
    imageUrl: "https://images.pokemontcg.io/base1/66.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/66_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "66",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-67",
    name: "Voltorb",
    imageUrl: "https://images.pokemontcg.io/base1/67.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/67_hires.png",
    types: ["Lightning"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "67",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-68",
    name: "Vulpix",
    imageUrl: "https://images.pokemontcg.io/base1/68.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/68_hires.png",
    types: ["Fire"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "68",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-69",
    name: "Weedle",
    imageUrl: "https://images.pokemontcg.io/base1/69.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/69_hires.png",
    types: ["Grass"],
    supertype: "Pokémon",
    subtype: "Basic",
    number: "69",
    artist: "Mitsuhiro Arita",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-70",
    name: "Clefairy Doll",
    imageUrl: "https://images.pokemontcg.io/base1/70.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/70_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "70",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-71",
    name: "Computer Search",
    imageUrl: "https://images.pokemontcg.io/base1/71.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/71_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "71",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-72",
    name: "Devolution Spray",
    imageUrl: "https://images.pokemontcg.io/base1/72.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/72_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "72",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-73",
    name: "Impostor ProfessorO ak",
    imageUrl: "https://images.pokemontcg.io/base1/73.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/73_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "73",
    artist: "Ken Sugimori",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-74",
    name: "Item Finder",
    imageUrl: "https://images.pokemontcg.io/base1/74.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/74_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "74",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-75",
    name: "Lass",
    imageUrl: "https://images.pokemontcg.io/base1/75.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/75_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "75",
    artist: "Ken Sugimori",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-76",
    name: "Pokémon Breeder",
    imageUrl: "https://images.pokemontcg.io/base1/76.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/76_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "76",
    artist: "Ken Sugimori",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-77",
    name: "Pokémon Trader",
    imageUrl: "https://images.pokemontcg.io/base1/77.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/77_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "77",
    artist: "Ken Sugimori",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-78",
    name: "Scoop Up",
    imageUrl: "https://images.pokemontcg.io/base1/78.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/78_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "78",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-79",
    name: "Super Energy Removal",
    imageUrl: "https://images.pokemontcg.io/base1/79.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/79_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "79",
    artist: "Keiji Kinebuchi",
    rarity: "Rare",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-80",
    name: "Defender",
    imageUrl: "https://images.pokemontcg.io/base1/80.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/80_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "80",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-81",
    name: "Energy Retrieval",
    imageUrl: "https://images.pokemontcg.io/base1/81.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/81_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "81",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-82",
    name: "Full Heal",
    imageUrl: "https://images.pokemontcg.io/base1/82.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/82_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "82",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-83",
    name: "Maintenance",
    imageUrl: "https://images.pokemontcg.io/base1/83.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/83_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "83",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-84",
    name: "Plus Power",
    imageUrl: "https://images.pokemontcg.io/base1/84.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/84_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "84",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-85",
    name: "Pokémon Center",
    imageUrl: "https://images.pokemontcg.io/base1/85.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/85_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "85",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-86",
    name: "Pokémon Flute",
    imageUrl: "https://images.pokemontcg.io/base1/86.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/86_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "86",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-87",
    name: "Pokédex",
    imageUrl: "https://images.pokemontcg.io/base1/87.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/87_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "87",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-88",
    name: "Professor Oak",
    imageUrl: "https://images.pokemontcg.io/base1/88.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/88_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "88",
    artist: "Ken Sugimori",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-89",
    name: "Revive",
    imageUrl: "https://images.pokemontcg.io/base1/89.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/89_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "89",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-90",
    name: "Super Potion",
    imageUrl: "https://images.pokemontcg.io/base1/90.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/90_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "90",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-91",
    name: "Bill",
    imageUrl: "https://images.pokemontcg.io/base1/91.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/91_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "91",
    artist: "Ken Sugimori",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-92",
    name: "Energy Removal",
    imageUrl: "https://images.pokemontcg.io/base1/92.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/92_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "92",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-93",
    name: "Gust of Wind",
    imageUrl: "https://images.pokemontcg.io/base1/93.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/93_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "93",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-94",
    name: "Potion",
    imageUrl: "https://images.pokemontcg.io/base1/94.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/94_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "94",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-95",
    name: "Switch",
    imageUrl: "https://images.pokemontcg.io/base1/95.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/95_hires.png",
    supertype: "Trainer",
    subtype: "",
    number: "95",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-96",
    name: "Double Colorless Energy",
    imageUrl: "https://images.pokemontcg.io/base1/96.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/96_hires.png",
    supertype: "Energy",
    subtype: "Special",
    number: "96",
    artist: "Keiji Kinebuchi",
    rarity: "Uncommon",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-97",
    name: "Fighting Energy",
    imageUrl: "https://images.pokemontcg.io/base1/97.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/97_hires.png",
    supertype: "Energy",
    subtype: "Basic",
    number: "97",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-98",
    name: "Fire Energy",
    imageUrl: "https://images.pokemontcg.io/base1/98.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/98_hires.png",
    supertype: "Energy",
    subtype: "Basic",
    number: "98",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-99",
    name: "Grass Energy",
    imageUrl: "https://images.pokemontcg.io/base1/99.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/99_hires.png",
    supertype: "Energy",
    subtype: "Basic",
    number: "99",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-100",
    name: "Lightning Energy",
    imageUrl: "https://images.pokemontcg.io/base1/100.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/100_hires.png",
    supertype: "Energy",
    subtype: "Basic",
    number: "100",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-101",
    name: "Psychic Energy",
    imageUrl: "https://images.pokemontcg.io/base1/101.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/101_hires.png",
    supertype: "Energy",
    subtype: "Basic",
    number: "101",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
  {
    id: "base1-102",
    name: "Water Energy",
    imageUrl: "https://images.pokemontcg.io/base1/102.png",
    imageUrlHiRes: "https://images.pokemontcg.io/base1/102_hires.png",
    supertype: "Energy",
    subtype: "Basic",
    number: "102",
    artist: "Keiji Kinebuchi",
    rarity: "Common",
    series: "Base",
    set: "Base",
    setCode: "base1",
  },
];
